### ISSUE TITLE
 Error: Cannot find module '@fullhuman/postcss-purgecss'

### ISSUE THREAD

**Issue by Batsirai** [matzeso/quasar-app-extension-tailwindcss#1]
After installing the extension, I run $ quasar dev and I get:

` app:extension Running "tailwindcss" Quasar App Extension... +6ms
(node:80905) UnhandledPromiseRejectionWarning:   Error: Cannot find module '@fullhuman/postcss-purgecss'
  
  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15
  
  - loader.js:507 Function.Module._load
    internal/modules/cjs/loader.js:507:25
  
  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17
  
  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18
  
  - index.js:17 module.exports
    [ui]/[quasar-app-extension-tailwindcss]/src/index.js:17:22
  
  - Extension.js:225 Extension.run
    [ui]/[@quasar]/app/lib/app-extension/Extension.js:225:11
  
  - extensions-runner.js:16 ExtensionsRunner.registerExtensions
    [ui]/[@quasar]/app/lib/app-extension/extensions-runner.js:16:31
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  
  - loader.js:745 Function.Module.runMain
    internal/modules/cjs/loader.js:745:11
  
  - node.js:266 startup
    internal/bootstrap/node.js:266:19
  

(node:80905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:80905) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Hope you can help... it was a working and fairly clean app before.

**Comment by matzeso** [comment]
Hey, sorry for the late reply. Thanks. Something must have broken in the new version. I will look into it.

**Comment by matzeso** [comment]
Fixed and published in 0.1.5
