### ISSUE TITLE
Tailwind UI

### ISSUE THREAD

**Issue by Batsirai** [matzeso/quasar-app-extension-tailwindcss#2]
it would be great if Quasar components could take the TailwindUI styles and use those over default Quasar Material UI Style, or even overwrite the Quasar css... 
or prevent its compiling?

Great package!

**Comment by LinnaeK** [comment]
Yes, thank you for this package! I want to second Batsirai pull request to make it possible for TailwindUI styles and classes to override the defaults. If you have suggestions on how to accomplish this outside of modifying your extension any recommendations you may have would be greatly appreciated. Thank you!

**Comment by matthias-influry** [comment]
Hey, I read those wishes before in the Quasar repository. Unfortunately, last time I checked the Quasar team is not planning on exchanging their own styles, especially because it would break backwards compatibility.
See https://github.com/quasarframework/quasar/issues/5618 where pdanpdan mentions it won't get replaced.

**Comment by MordantWastrel** [comment]
It makes sense that they would not implement a breaking change in a minor release, but it appears that this has gone onto the milestone list for 2.0 based on this issue:

https://github.com/quasarframework/quasar/issues/6775

https://github.com/quasarframework/quasar/milestone/57

**Comment by matzeso** [comment]
We can re-open this discussion once Quasar allows to exchange this. As of now, there is nothing I can do from this side to support it. This is just an extension and not affiliated with the official Quasar Framework development. 
You can raise your concerns in their repository in the links mentioned above :-)
