### ISSUE TITLE
How do we upgrade to Tailwind 2.0?

### ISSUE THREAD

**Issue by fergusmeiklejohn** [matzeso/quasar-app-extension-tailwindcss#7]
Doing a straight install as per the Tailwind upgrade docs doesn't work. I'm getting postcss error: `PostCSS plugin autoprefixer requires PostCSS 8.` but I've installed `"postcss": "^8.1.8",`

**Comment by matzeso** [comment]
Hey, 
I tried the same. To no prevail.
Since quasar still depends on PostCSS 7 there is currently no way that I know of on how to fix this.
I already created a new Version of the extension using TailwindCSS^2.0.0, but it won't work with the current version of Quasar.
Once the quasar dependencies are updated, you can install the new version of this extension to make use of Tailwind v2.

**Comment by jits** [comment]
Hi – note that [Tailwind 2 has a PostCSS 7 compat build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) which _could_ be used/integrated instead?

**Comment by fergusmeiklejohn** [comment]
@jits @matzeso 
I tried the compatibility build and it works! BUT.. there are some strange behaviours. `gray-50` doesn't exist, which make me think I'm still using v1.x of tailwind,  and it's messing up Quasar's styling...
![Screenshot 2020-11-21 at 13 03 42](https://user-images.githubusercontent.com/11864025/99868108-8a79f980-2bfa-11eb-94d4-bb3541e26338.png)
![Screenshot 2020-11-21 at 13 00 42](https://user-images.githubusercontent.com/11864025/99868110-8bab2680-2bfa-11eb-815e-8756dab5def6.png)
![Screenshot 2020-11-21 at 13 00 32](https://user-images.githubusercontent.com/11864025/99868111-8c43bd00-2bfa-11eb-81ce-6f84de3370db.png)

**Comment by matzeso** [comment]
Thank you @jits for mentioning that, I didn't see that.
I updated this extension to use the compat build, tested it and it works. So now you can use TailwindCSS v2. As for your compatibility issues @fergusmeiklejohn  I mentioned this issue in the readme and let the user decide what to do. 
With 
`quasar ext install taildindcss@^1.0.0` you can still install the old extension which uses TailwindCSS v1.
Thanks to you both.

**Comment by jits** [comment]
Great! Thanks @matzeso for your efforts on this library – much appreciated.
